name: Cron newInsight

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  call-newInsight-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Ejecutar script
        env:
          API_URL: ${{ secrets.API_URL }}
          INTERNAL_TOKEN: ${{ secrets.INTERNAL_TOKEN }}
        run: node scripts/insertInsight.js